### ISSUE TITLE
Deserializer for declaration public kotlinx.coroutines/SingleThreadDispatcher|null[0] is not found

### ISSUE THREAD

**Issue by schmidt9** [korlibs/korio#106]
Getting this error when using Cocoapods, please refer to this issues
https://youtrack.jetbrains.com/issue/KT-41378
https://youtrack.jetbrains.com/issue/KT-41776
Possible workaround 
https://youtrack.jetbrains.com/issue/KT-41378#focus=Comments-27-4362009.0-0

**Comment by soywiz** [comment]
Thanks for reporting! I will investigate 👍

**Comment by ArtRoman** [comment]
I have to use 'kotlinx-coroutines-core:1.3.9-native-mt-2' with { force = true } — that's because korio adds transitive dependency to default version of kotlinx-coroutines-core:1.3.9 instead of 'native-mt' version.

So, my current config is next for common module (groovy):
```Groovy
implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.9-native-mt-2") { force = true }
implementation "org.jetbrains.kotlinx:kotlinx-serialization-json:1.0.0"
implementation "com.soywiz.korlibs.korio:korio:1.12.0"
implementation "com.soywiz.korlibs.klock:klock:1.12.1"
```

**Comment by soywiz** [comment]
@ArtRoman do you know if there is something I can do at the Korio level? By using native-mt-2 directly would be enough, or would cause problems to other people?

**Comment by ArtRoman** [comment]
> By using native-mt-2 directly would be enough, or would cause problems to other people?

This will cause upgrade to native-mt version for all users, which is not expected. 

It's an issue of dependency transitivity in multiplatform projects. Ktor 1.4.1 is depends on 1.3.9-native-mt-2, but it downgrades to 1.3.9 if I'm using clean 1.3.9 version, and upgrades to 'native-mt-2' even if I'm declaring use of 'native-mt' (without "-2"). Enabling korio dependency downgrades coroutines back to 1.3.9 for all targets.

The coroutines library in native-mt branch has [recomendation](https://github.com/Kotlin/kotlinx.coroutines/tree/native-mt#native) to set `kotlin.mpp.enableGranularSourceSetsMetadata=true` in gradle.properties to get different dependencies for different targets. The same recommendation has [migration to kotlin 1.4](https://kotlinlang.org/docs/reference/migrating-multiplatform-project-to-14.html#for-library-authors) manual. With this option enabled I've got both version of coroutines for core, clean version for jvm and native-mt version for native target. But native build still uses clean version because of korio. I think you should enable this after testing.

**Comment by soywiz** [comment]
Not sure if this is still an issue, but I'm going to close this since this should be handled on the Kotlin or Kotlinx.coroutines side since I can only choose one version of the library and it should be the most standard one
