### ISSUE TITLE
I am Getting "Supertypes of the following classes cannot be resolved." error!

### ISSUE THREAD

**Issue by min2222** [korlibs/korio#120]
Hi I am trying to decompress .imy file in Criminal Girls. 
I created a new project with the code you fixed and most of them work successfully, 
but when I try to run the most important encodeTest() method, 
I get an error. 
How to Fix it?
I will attach an my project and error log

[criminalgirls.zip](https://github.com/korlibs/korio/files/6222326/criminalgirls.zip)

**Comment by soywiz** [comment]
Hey @min2222 As stated here: https://github.com/talestra/talestrakt/issues/1 you are on you own. That code was written more than 3 years ago and I'm not maintaining it. It is using Korio `0.11.0` (now we are on `2.0.10`) ! which is ultra-hyper-mega-outdated. It uses an old `kotlinx.coroutines` version and an old `Kotlin` version which is binary incompatible due to experimental coroutines. I'm sorry about that, but I instruct you to stop creating issues on the korlibs organization since here we are only supporting the latest 2.x version.
As said in the other issue, you can try to copy the `IMY.kt` file into a new project using the latest version of Kotlin, Korio and Korim. It might work, but even if not these Github issues are not a supporting channel, and I'm not supporting the code either. Sorry.

**Comment by min2222** [comment]
Okay, but I have a question. There is a method called syncTest in the old version (0.11.0), but not in the latest version (2.0.10). What should I use instead of this method?

**Comment by soywiz** [comment]
I guess it is called `suspendTest`
