### ISSUE TITLE
WebSocketClient suspends forever on send

### ISSUE THREAD

**Issue by Chazoshtare** [korlibs/korio#147]
I created a very simple project to test WebSocketClient, as follows:
```
fun main() = runBlocking {
    val ws = WebSocketClient("ws://localhost:8080")
    ws.send("1234")
    val received = ws.readString()
    println(received)
    ws.close()
}
```
I tried testing it against an echo websocket server, but it just suspends forever on first `ws.send()` call. Nothing is actually sent, so nothing is received by the server and client.
I tested it on linuxX64 and mingwX64, doesn't work on both.

JS echo server: [server.zip](https://github.com/korlibs/korio/files/7315817/server.zip)
KorIO client: [wstest.zip](https://github.com/korlibs/korio/files/7315826/wstest.zip)

**Comment by soywiz** [comment]
Fixed in korge-next:

```kotlin
suspend fun main() {
	val ws = WebSocketClient("ws://localhost:8080") {
		onOpen { println("OPEN") }
		onError { println("ERROR: $it") }
		onClose { println("CLOSED") }
	}
	val strings = ws.messageChannel()
	println("[1]")
	ws.send("1234")
	println("[2]")
	val received = strings.receive()
	//val received = ws.readString()
	println("[3]")
	println(received)
	//ws.close()
	println("[4]")
}
```

I have deprecated `ws.readString`. because it wouldn't work in your case because the readString would force the message to be sent later. The messageChannel allows to register and read one by one

Also notice that the server is sending a binary message instead of a text message despite of the text being sent by the client:

```js
const WebSocket = require('ws');
const wss = new WebSocket.Server({port: 8080});

wss.on('connection', socket => {
    console.log("connected")
    socket.on('close', () => {
        console.log("close")
    })
    socket.on('message', data => {
        console.log(data);
        socket.send(data.toString());
    });
});

console.log(`Listening on ws://localhost:8080`);
```

The other issue was that `ws.js` is enforcing keys to be 16-byte length, and was not the case for the korio implementation that by default had a smaller key.
