### ISSUE TITLE
how to use AsyncQueue, invoke is sync

### ISSUE THREAD

**Issue by chinacharis** [korlibs/korio#24]
how to use AsyncQueue, invoke is sync, can you explain to me? thanks.

**Comment by soywiz** [comment]
I have added a test that should serve as a sample of usage too: https://github.com/korlibs/korio/commit/0940451de5578ee837b57f34dbfa490119f2aef4

It launches and queues blocks of code to be executed in order. So they are not executes immediately, but in some point in the future.

**Comment by chinacharis** [comment]
OK，Thanks, Can you give a test sample in JS?
let asyncQueue = new korio.com.soywiz.korio.async.AsyncQueueWithContext(new korio.com.soywiz.korio.async.AsyncQueue(), korio.com.soywiz.korio.async.KorioDefaultDispatcher);

next ?

**Comment by soywiz** [comment]
What do you mean by test sample in JS? Are you consuming korio from JS? Or using Kotlin and generating JS with KotlinJS target?

**Comment by chinacharis** [comment]
I Build Korio with jsJar target, generate korio-js-1.0.0-alpha-2.jar, using:

<script src="lib/kotlin.js"></script>
<script src="lib/kotlinx-coroutines-core.js"></script>
<script src="lib/kotlinx-atomicfu.js"></script>
<script src="lib/kotlinx-html-js.js"></script>
<script src="lib/kmem.js"></script>
<script src="lib/kds.js"></script>
<script src="lib/klock.js"></script>
<script src="lib/korio.js"></script>

let asyncQueue = new korio.com.soywiz.korio.async.AsyncQueueWithContext(new korio.com.soywiz.korio.async.AsyncQueue(), korio.com.soywiz.korio.async.KorioDefaultDispatcher);

next ? or give a sample, Thanks.

**Comment by soywiz** [comment]
Sorry, it seems that I forgot to reply.

Never tried to use Kotlin.JS from JS directly except for calling very specific functions. Your best bet is to write the code in Kotlin.JS directly.

If you plan to write asynchronous code in JS, your best bet is to use Promises and async functions (await+async) from ES2017: http://kangax.github.io/compat-table/es2016plus/#test-async_functions Most modern browsers support it already and probably you can transpile it if you need to support older browsers.

I'm closing this since it is not related to korio, but to bidirectional interoperability between JS and Kotlin.JS. And I do not plan to do special work to make korio callable from JS since the korlibs objective is to write code in Kotlin common directly.
