### ISSUE TITLE
Jar from bintray is empty

### ISSUE THREAD

**Issue by martmists** [korlibs/korio#38]
Jar as shown in IntelliJ
![Screenshot_20191215_174152](https://user-images.githubusercontent.com/16361449/70865825-308ca080-1f62-11ea-9072-bdaf8a0fba1f.png)

Line in build.gradle (copied from bintray)
![Screenshot_20191215_174214](https://user-images.githubusercontent.com/16361449/70865832-3d10f900-1f62-11ea-9bb4-091b65761b01.png)

**Comment by soywiz** [comment]
This is a multiplatform project using gradle metadata.
If you are using it in another multiplatform project, you should include: `enableFeaturePreview('GRADLE_METADATA')`

Like here:
https://github.com/korlibs/korio/blob/9da03fcd6fd110332d3b08419bcd172cba338de9/settings.gradle#L13

If you are using only on the JVM, you are including the wrong artifact. `korio` is empty because only the metadata is used. The right artifact for jvm is `korio-jvm`.

Here:
https://bintray.com/package/files/korlibs/korlibs/korio?order=asc&sort=name&basePath=com%2Fsoywiz%2Fkorlibs%2Fkorio%2Fkorio-jvm%2F1.9.6&tab=files

It is possible that the documentation is outdated since I have been changing the code to adapt to the Kotlin changes since multiplatform is still experimental.
