### ISSUE TITLE
Explanation runBlockingNoSuspensions ()

### ISSUE THREAD

**Issue by lemkoleg** [korlibs/korio#48]
Hello. Explanation, please, to me the purpose of the function runBlockingNoSuspensions ().
I assume that it makes asynchronous function calls synchronous.
But when I run the function main():

  val connection: RawSocketWebSocketClient

  fun setConn(connectionIpAddress: String, сonnPort: Int):RawSocketWebSocketClient = runBlockingNoSuspensions{
        var cl  = createTcpClient()
        cl.connect(connectionIpAddress, сonnPort)
        val s = RawSocketWebSocketClient(
            GlobalScope.coroutineContext, cl!!, URL.invoke(""), null, false, null, ""
        )
        return@runBlockingNoSuspensions s
    }
	
	fun main(){
	  GlobalScope.launch { 
	  val connection = setConn("localHostName",22236)
	  println(connection.host)
	  }
	}
	
I get an error: 
com.soywiz.korio.lang.InvalidOperationException: runBlockingNoSuspensions was not completed synchronously! suspendCount=1

**Comment by soywiz** [comment]
If you want to wait blocking the thread, you have to use `runBlocking` from kotlinx.coroutines (and that's not available at common)
You can make your main `suspend fun` or `fun main() = Korio { }` on the entry point.
You should make `suspend fun setConn` so `runBlocking` is not needed there.

`runBlockingNoSuspensions` is designed to be able to call methods that normally suspend, but they don't because you are reading from memory. That's used for example to do (un)compressing in-memory.
